# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - '*'

variables: 
  isTag: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]


pool:
  vmImage: ubuntu-latest

stages:
  - stage: Install_Test
    jobs:
      - job: Install_Test
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '14.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
            npm test
          displayName: 'npm install and test'

  - stage: Publish
    condition: and(succeeded(), eq(variables.isTag, true))
    jobs:
    - job: Publish
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '14.x'
          displayName: 'Install Node.js'
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              npm publish
          env:
            NPM_PUBLISH_KEY_PAT: $(NPM_PUBLISH_KEY_PAT)